#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/edgedesk/edgedesk /usr/bin/edgedesk

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/edgedesk.service ]; then
			rm -f /etc/systemd/system/edgedesk.service /usr/lib/systemd/system/edgedesk.service /usr/lib/systemd/user/edgedesk.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/edgedesk/files/systemd/edgedesk.service /usr/lib/systemd/system/edgedesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload edgedesk.service: Unit edgedesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/edgedesk.service:10: Executable path is not absolute: pkill -f "edgedesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/edgedesk.service
		fi
		systemctl daemon-reload
		systemctl enable edgedesk
		systemctl start edgedesk
	fi
fi
